import streamlit as st

st.markdown("<h1 style='text-align: center;'>Experiências</h1>", unsafe_allow_html=True)

with st.expander('Programação e Pesquisa'):
    st.write(' - Grande parte da minha experiência com programação foi construída a partir de estudos próprios. Por curiosidade, costumo consumir muito conteúdo relacionado ao assunto, desde vídeos/tutoriais, até artigos/notícias. E, com o constante fluxo de ideias e experiência, escolho projetos próprios para enfrentar (como os projetos descritos na ana Projetos). Esse costume me ajuda a desenvolver independência e resiliência, além de incentivar minha criatividade a vir à tona.')

    st.write(' - Além de projetos próprios, construí um projeto de pesquina no CNPEM-LNBR (lar do maior acelerador de partículas da América Latina, Sirius), junto com meu orientador, Carlos Eduardo Driemeier, onde estudei e desenvolvi a aplicação de técnincas de machine learning à previsão da energia de ativação de reações quíimicas de lignina.')
    st.write(' - O projeto em questão garantiu que eu tivesse contato profunda com uma gama de conhecimentos , os quais eu não teria normalmente, entre eles: conceitos de químicca quântica computacional, técnincas de manipulação e engenharia de dados, técnincas de transfer learning e visualização de dados. Além da grande experiência que adquiri, escrevi relatórios e construí inúmeras apresentações de critério científico, desenvolvendo habilidades de comunicação científica e poder de síntese.')


with st.expander('Liderança e Trabalho em Equipe'):
    st.write(' - No período de novembro de 2022 a novembro de 2023, assumi o cargo de vice-presidência da gestão admnistrativa da bateria PercUrsão, entidade ativa dentro da Unicamp, a qual possui o objetivo de expandir o alcance da cultura do samba (e outros ritmos) dentro da universidade, a partir de apresentações e eventos. Durante esse período, houve a necessidade de lidar com reuniões semanais, construção de atas e relatórios, organização de eventos (tanto logística, quanto financeiramente), construção e manutenção de relações burocráticas com os órgãos oficias da universidade e, em meio a isso, organização e liderança do resto do grupo de gestão, composto por Diretorias de Patrimônio, Financeiro, Marketing, Produos e Eventos. Hoje sou Conselho da atual gestão e atuo na gestão rítmica da bateria, onde sou Diretor do meu instrumento.')
    st.write(' - Além da experiência na bateria, componho a gestão do grupo de estudos em IA e Data Science, Iris, o qual possui oobjetivo de fomentar e desenvolver uma comunidade ativa sobre o tópico dentro da universidade. No cargo, lido com a organização de reuniões, construção de atas, organização logística e financeira, elaboração/idealização e execução de projetos envolvendo a área, constato com empresas interessadas na área e a necessidade de se manter atualizado ,constantemente, sobre o mundo da IA e da Data Science. A gestão da Iris carrega um desafio além da pura manutenção: a expansão da entidade, visto que, em quesitos de gestão, somos poucas pessoas e não ppssuímos um caixa financeiro da entidade. O meu objetivo é que, até o fim da miha gestão, a entidade tenha alcance para toda a Unicamp, possua um caixa financeito próprio e sustentável e uma gestão estruturada formalmente.')
